### ISSUE TITLE
Adding OData Connected Service to the project failed: Value cannot be null. Parameter name: path1

### ISSUE THREAD

**Issue by dalehhirt** [OData/lab#82] opened 2018-03-12 17:47 UTC
When attempting to add a new Rest API client proxy, this error pops up.  What is the resolution or action item?  This error is pretty vague and non-helpful.

**Comment by tcukanoot** [comment] 2018-03-21 18:08
Seems to be a common issue. I'm also looking for a resolution. Visual Studio 2017.
https://github.com/OData/lab/issues/56
https://github.com/OData/lab/issues/64

**Comment by dalehhirt** [comment] 2018-03-21 18:38
@tcukanoot this is what worked for me:

First install Microsoft WCF Toolkit from the link below:
[WCF Toolkit](https://download.microsoft.com/download/1/C/A/1CAA41C7-88B9-42D6-9E11-3C655656DAB1/WcfDataServices.exe)

and then go to the registry, find the following key:
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft WCF Data Services]
and create a duplicate of "5.6" named "VS 2014 Tooling".

**Comment by tcukanoot** [comment] 2018-03-21 19:14
@dalehhirt 

Thanks for the response. I've tried that as well, but still no luck. I'm wondering if it's due to a lack of credentials supplied.
If I hit the URL directly, I still get a 'cannot access' error. Then if I save the metadata xml locally and point to it, I get a 'closed textwriter' error.  Having to go the VS 2015 route for now.

**Comment by tfujii** [comment] 2018-04-03 05:36
It looks like the solution from @dalehhirt works with OData services that do not require authentication.

**Comment by AlanWong-MS** [comment] 2018-04-03 18:28
The extension currently doesn't support authentication. The feature is highly requested and is in a pending state.

**Comment by AlanWong-MS** [comment] 2018-04-03 18:29
Since the original issue has been resolved, closing this thread.

**Closed as completed by AlanWong-MS** 2018-04-03 18:29 UTC
Labels: P4

**Comment by tfujii** [comment] 2018-04-03 18:54
@AlanWong-MS May I request that the instructions from @dalehhirt be added to an FAQ so that other developers using VS 2017 may find this solution? It seems like the easiest one out of the set I've seen elsewhere in the issues, and I'm concerned that it may end up getting buried beneath the other more complex solutions proposed in the other threads.

**Comment by AlanWong-MS** [comment] 2018-04-03 19:59
@tfujii, I can do that. Thanks for the suggestion! Adding a FAQ through #84 to the ReadMe.

**Comment by onyangofred** [comment] 2018-05-02 08:05
Just open the link in Internet explorer, will prompt for username and password. Then save the credentials. Try again in visual studio. It works!!!

**Comment by Koochy87** [comment] 2018-05-03 06:36
@onyangofred  I openned it, saved it, tried it in VS but it didn't work. An "Object reference not set to an instance of an object" error appeared.

**Comment by Orbatis** [comment] 2018-05-08 07:03
I tried to install a component manually (Microsoft.OData.ConnectedService.vsix) but I have the same problem! An "Object reference not set to an instance of an object" error appeared.

**Comment by mPisano** [comment] 2018-05-24 02:35
@dalehhirt 

two thumbs up!!!

and then go to the registry, find the following key:
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft WCF Data Services]
and create a duplicate of "5.6" named "VS 2014 Tooling".

Export the reg and edit file and merge it back and vs2017 is fixed!!!!

**Comment by mazenkt** [comment] 2018-05-24 11:13
Just call the URL in explorer like this: https://........:xx/TSOL/OData/$metadata
- Save the file on local machine.
- Use the file path in Address for Configration endpoint.

This work for me.

**Comment by soerenBoisen** [comment] 2018-09-03 10:36
@AlanWong-MS I just ran into this issue when using a local EDMX file when trying to work around the lack of support for authentication (sigh). Could you please clarify how this issue was resolved? Because the workaround provided by @dalehhirt is arcane and inconvenient.
Why does the extension require this complex manual setup? This issue should be reopened and remain open until the extension solves this problem in a proper way.

**Comment by gtrennert** [comment] 2019-07-27 10:03
I followed all this indications and nothing works. Is there any tool to add a odata reference to a c# application on VS2017 or VS2019 ? How comes that this issue is closed but nothing works ?

**Comment by mPisano** [comment] 2019-07-27 13:24
I think it's closed because most people have shifted from WCF to either the OData v1-3 or the Newer OData V4 Client Generator for Odata
See
https://marketplace.visualstudio.com/items?itemName=bingl.ODatav4ClientCodeGenerator 

HTH
Mike

**Comment by unchase** [comment] 2019-07-27 20:11
Hello. You just can use [Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) to solve your issue.

**Comment by EdwinRono-254** [comment] 2022-07-28 18:08
> I think it's closed because most people have shifted from WCF to either the OData v1-3 or the Newer OData V4 Client Generator for Odata See https://marketplace.visualstudio.com/items?itemName=bingl.ODatav4ClientCodeGenerator
> 
> HTH Mike


This resolved my issue. Thanks

**Comment by EdwinRono-254** [comment] 2022-07-28 18:16
> Hello. You just can use [Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) to solve your issue.

I am getting below error when I use Unchase ---------------------------

Microsoft Visual Studio
---------------------------
Connected Services

Cannot access http://localhost:7048/BusinessCentral/ODataV4/$metadata
Exception message: "The remote server returned an error: (401) Unauthorized.".
---------------------------
OK   
---------------------------
